# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- none

resources:
- repo: self

stages:
- stage: Deploy
  displayName: Deploy stage

  jobs:
    - job: Deploy
      displayName: Deploy
      pool: integrant_pool
      steps:
      - task: HelmInstaller@0
        inputs:
          helmVersion: '2.14.1'
          installKubectl: true
      
      - task: HelmDeploy@0
        inputs:
          connectionType: 'Azure Resource Manager'
          azureSubscription: 'Azure subscription 1(55c1414d-3b8b-4d28-97dc-e1b30e341084)'
          azureResourceGroup: 'trn-prj-1'
          kubernetesCluster: 'integrant-training-cluster'
          command: upgrade
          chartType: FilePath
          chartPath: $(System.DefaultWorkingDirectory)/frontend-chart
          releaseName: frontend
          waitForExecution: false
          install: true