apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: 
      selfHeal: true
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: config-aws-dev
    repoURL: https://eu-de.git.cloud.ibm.com/raseedyops/cluster-applications.git 
    # repoURL: github.com/argoproj/argo-events/manifests/cluster-install
    targetRevision: HEAD