apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kong/kong
    # helm:
    #   valueFiles:
    #   - values.yaml
    # repoURL: https://helm.elastic.co
    # targetRevision: 7.6.1
