trigger:
- none
variables:
 pool: integrant_pool

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: BuildSite
        displayName: Build Site
        pool: $(pool)

        steps:
          - script: dotnet build --configuration Release
            displayName: 'Build'

          - task: DotNetCoreCLI@2
            inputs:
              command: publish
              publishWebProjects: True
              arguments: '--configuration Release --framework net6.0 --runtime linux-x64 --self-contained --output $(Build.ArtifactStagingDirectory)'
              zipAfterPublish: True
          - task: PublishPipelineArtifact@0
            displayName: 'Publish site pipeline artifacts'
            inputs:
              artifactName: "$(Build.BuildId)-Api"
              targetPath: $(Build.ArtifactStagingDirectory)
              
          - task: AzureWebApp@1
            inputs:
                azureSubscription: 'Azure subscription 1(55c1414d-3b8b-4d28-97dc-e1b30e341084)'
                appType: webAppLinux
                appName: 'api-proj'
                package: '$(Build.ArtifactStagingDirectory)/*.zip'
                runtimeStack: 'DOTNETCORE|6.0'