apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kong
    repoURL: https://github.com/mikesparr/gcp-cicd-demo-config
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true