apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aam-live-prod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: 
      selfHeal: true
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlay/prod
    repoURL: https://github.com/amr158/ArgoCD-Kustomize-Demo
    targetRevision: HEAD