resources:
  - env.yaml
  - namespaces.yaml
  - application-kong-helm.yaml
  - application-tick-stack.yaml
  - application-apps-dev.yaml
  - application-apps-test.yaml
  # - ingress-all.yaml

  # - applicaiton-prometheus.yaml


# configMapGenerator:
#   - name: env
#     op: add
#     literals:
#       - domain=aam.com


replacements:
  - source:
      kind: ConfigMap
      name: env
      fieldPath: data.domain
    targets:
      - select:
          kind: Ingress
          labelSelector: 'type=app'
        fieldPaths:
          - spec.rules.*.host
        options:
          delimiter: '.' 
          index: 10
      - select:
          kind: Ingress
          labelSelector: 'type=api'
        fieldPaths:
          - spec.rules.*.host