apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: demo-app
spec:
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31214
      protocol: TCP
  selector:
    app: backend-dep