apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dep
  namespace: demo-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: backend
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 500m

      
